routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('SeksEd');

Route::get('/videos/get/{id}', 'PagesController@getMoviesByCategory');

Route::get('/info', 'PagesController@showInfo');
Route::get('/vagina', 'PagesController@showVagina');
Route::get('/penis', 'PagesController@showPenis');

Route::get('/info/admin', 'PagesController@showAdmin');

//Route::resource('/movies', 'MoviesController');

//Route::post('/movies', 'MoviesController@store');

//Route::get('get-video/{video}', 'MoviesController@getVideo')->name('getVideo');

/*Route::get('/upload/something', [
    'as' => 'movie',
    'uses' => 'MoviesController@show'
]);*/


Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function(){
    Route::resource('videos', 'Admin\VideoController');
    Route::resource('links', 'Admin\LinkController');
    Route::resource('info', 'Admin\InfoController');
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
});

app/models/Info.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Info extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Admin/InfoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\models\Info;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\Http\Controllers\Controller;

class InfoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $infos = Info::all();
        return view('admin.info.index', compact('infos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.info.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        Info::create($request->all());
        return redirect()->route('admin.info.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Info $info
     * @return Response
     */
    public function show(Info $info)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Info $info
     * @return Response
     */
    public function edit(Info $info)
    {
        return view('admin.info.edit', compact('info'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Info $info
     * @return Response
     */
    public function update(Request $request, Info $info)
    {
        $info->update($request->all());
        return redirect()->route('admin.info.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Info $info
     * @return Response
     */
    public function destroy(Info $info)
    {
        $info->delete();
        return redirect()->route('admin.info.index');
    }
}

resources/views/admin/info/create.blade.php
@extends('layouts.adminlayout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Nieuwe info toevoegen</div>

                <div class="card-body">

                    <form method="POST" action="{{route('admin.info.store')}}" enctype="multipart/form-data" name="infoForm">
                        @csrf
                        <div class="field">
                            Titel:
                            <input type="text" name="title" class="form-control" />
                            Tekst:
                            <input type="text" name="text" class="form-control" />

                            <br />

                            <input type="submit" value="Bewaar" id="createInfoFormSubmitBtn" class="btn btn-primary"/>
                            <a value="Annuleer" class="btn btn-primary btn-close" href="{{route('admin.info.index')}}"> Annuleer</a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/info/edit.blade.php
@extends('layouts.adminlayout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Video aanpassen</div>

                <div class="card-body">

                    <form method="POST" action="{{ route('admin.videos.update', $video->id) }}">
                        {{ method_field('PUT') }}
                        @csrf
                        Title:
                        <input type="text" name="title" value="{{$video->title}}" class="form-control" />
                        Categorie id:
                        <input type="text" name="categorie_id" value="{{$video->categorie_id}}" class="form-control" />
                        Beschrijving:
                        <input type="text" name="description" value="{{$video->description}}" class="form-control" />
                        Video URL:
                        <input type="text" name="movie_url" value="{{$video->movie_url}}" class="form-control" />
                        Rating:
                        <input type="text" name="rating" value="{{$video->rating}}" class="form-control" />

                        <br />

                        <input type="submit" value="Bewaar" class="btn btn-primary"/>
                        <a value="Annuleer" class="btn btn-primary btn-close" href="{{route('admin.videos.index')}}"> Annuleer</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/info/index.blade.php
@extends('layouts.adminlayout')

@section('content')
<div class="container">
    {{--<form>
        <div class="form-group">
            <textarea class="form-control" id="info-body"></textarea>
        </div>
        <button type="submit" class="btn btn-secondary">Opslaan</button>
    </form>--}}

    {{--<textarea id="my-editor" name="content" class="form-control">{!! old('content', 'test editor content') !!}</textarea>
    <script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
    <script>
        var options = {
            filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
            filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
            filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
            filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
        };
    </script>--}}
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Info</div>

                <div class="card-body">

                    <a href="{{route('admin.info.create')}}" class="btn btn-sm btn-primary">Nieuwe info toevoegen</a>
                    <br /><br />


                    <table class="table">
                        <tr>
                            <td>
                                Titel
                            </td>
                            <td>
                                Tekst
                            </td>
                        </tr>
                        @forelse($infos as $info)
                            <tr>
                                <td>
                                    {{ $info->title }}
                                </td>
                                <td>
                                    {{ $info->text }}
                                </td>
                                <td>
                                    <a href="{{ route('admin.info.edit', $info->id) }}" class="btn btn-sm btn-info">Edit</a>
                                    <form method="POST" action="{{ route('admin.info.destroy', $info->id) }}">
                                        @csrf
                                        {{ method_field('DELETE') }}
                                        <input type="submit" value="Delete" onclick="return confirm('Weet u zeker dat u de info wilt verwijderen?')"
                                               class="btn btn-sm btn-danger" />
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="2">
                                    Geen info gevonden.
                                </td>
                            </tr>
                        @endforelse
                    </table>

                </div>
            </div>
        </div>
    </div>

</div>

@endsection

@section('scriptsToLoad')
    <script src="{{ asset('vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
    <script>
        CKEDITOR.replace( 'info-body' );
    </script>

@endsection