routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('SeksEd');

Route::get('/videos/get/{id}', 'PagesController@getMoviesByCategory');

Route::get('/info', 'PagesController@showInfo');
Route::get('/vagina', 'PagesController@showVagina');
Route::get('/penis', 'PagesController@showPenis');

Route::get('/info/admin', 'PagesController@showAdmin');

//Route::resource('/movies', 'MoviesController');

//Route::post('/movies', 'MoviesController@store');

//Route::get('get-video/{video}', 'MoviesController@getVideo')->name('getVideo');

/*Route::get('/upload/something', [
    'as' => 'movie',
    'uses' => 'MoviesController@show'
]);*/


Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function(){
    Route::resource('videos', 'Admin\VideoController');
    Route::resource('links', 'Admin\LinkController');
    Route::resource('info', 'Admin\InfoController');
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
});

app/models/Link.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Admin/LinkController.php
<?php

namespace App\Http\Controllers\Admin;

use App\models\Link;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;

class LinkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $links = Link::all();
        return view('admin.links.index', compact('links'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.links.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        Link::create($request->all());
        return redirect()->route('admin.links.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Link  $link
     * @return Response
     */
    public function show(Link $link)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Link  $link
     * @return Response
     */
    public function edit(Link $link)
    {
        return view('admin.links.edit', compact('link'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  \App\Link  $link
     * @return Response
     */
    public function update(Request $request, Link $link)
    {
        $link->update($request->all());
        return redirect()->route('admin.links.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Link  $link
     * @return Response
     */
    public function destroy(Link $link)
    {
        $link->delete();
        return redirect()->route('admin.links.index');
    }
}

resources/views/admin/links/create.blade.php
@extends('layouts.adminlayout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Nieuwe link toevoegen</div>

                <div class="card-body">

                    <form method="POST" action="{{route('admin.links.store')}}" enctype="multipart/form-data" name="linkForm">
                        @csrf
                        <div class="field">
                            Organisatie:
                            <input type="text" name="organisatie" class="form-control" />
                            Website:
                            <input type="text" name="websitelink" class="form-control" />

                            <br />

                            <input type="submit" value="Bewaar" id="createLinkFormSubmitBtn" class="btn btn-primary"/>
                            <a value="Annuleer" class="btn btn-primary btn-close" href="{{route('admin.links.index')}}"> Annuleer</a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/links/edit.blade.php
@extends('layouts.adminlayout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Link aanpassen</div>

                <div class="card-body">

                    <form method="POST" action="{{ route('admin.links.update', $link->id) }}">
                        {{ method_field('PUT') }}
                        @csrf
                        Organisatie:
                        <input type="text" name="organisatie" value="{{$link->organisatie}}" class="form-control" />
                        Websitelink:
                        <input type="text" name="websitelink" value="{{$link->websitelink}}" class="form-control" />

                        <br />

                        <input type="submit" value="Bewaar" class="btn btn-primary"/>
                        <a value="Annuleer" class="btn btn-primary btn-close" href="{{route('admin.links.index')}}"> Annuleer</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/links/index.blade.php
@extends('layouts.adminlayout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Links</div>

                <div class="card-body">

                    <a href="{{route('admin.links.create')}}" class="btn btn-sm btn-primary">Nieuwe link toevoegen</a>
                    <br /><br />


                    <table class="table">
                        <tr>
                            <td>
                                Organisatie
                            </td>
                            <td>
                                Website
                            </td>
                        </tr>
                        @forelse($links as $link)
                            <tr>
                                <td>
                                    {{ $link->organisatie }}
                                </td>
                                <td>
                                    {{ $link->websitelink }}
                                </td>
                                <td>
                                    <a href="{{ route('admin.links.edit', $link->id) }}" class="btn btn-sm btn-info">Edit</a>
                                    <form method="POST" action="{{ route('admin.links.destroy', $link->id) }}">
                                        @csrf
                                        {{ method_field('DELETE') }}
                                        <input type="submit" value="Delete" onclick="return confirm('Weet u zeker dat u de link wilt verwijderen?')"
                                               class="btn btn-sm btn-danger" />
                                    </form>
                                </td>
                            </tr>
                            @empty
                        <tr>
                            <td colspan="2">
                                Geen links gevonden.
                            </td>
                        </tr>
                            @endforelse
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection