routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('SeksEd');

Route::get('/videos/get/{id}', 'PagesController@getMoviesByCategory');

Route::get('/info', 'PagesController@showInfo');
Route::get('/vagina', 'PagesController@showVagina');
Route::get('/penis', 'PagesController@showPenis');

Route::get('/info/admin', 'PagesController@showAdmin');

//Route::resource('/movies', 'MoviesController');

//Route::post('/movies', 'MoviesController@store');

//Route::get('get-video/{video}', 'MoviesController@getVideo')->name('getVideo');

/*Route::get('/upload/something', [
    'as' => 'movie',
    'uses' => 'MoviesController@show'
]);*/


Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function(){
    Route::resource('videos', 'Admin\VideoController');
    Route::resource('links', 'Admin\LinkController');
    Route::resource('info', 'Admin\InfoController');
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
});

app/models/Video.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;
use Nexmo\Message\Query;

class Video extends Model
{
    protected $guarded = [];

    public static function getRandomMoviesByRating(){

        $maxNumberOfMovies = "10";
        $randomMoviesByRating = Video::all()->random($maxNumberOfMovies)->sortByDesc("rating");
        return $randomMoviesByRating;

    }

    public function categorie()
    {
        return $this->belongsTo('App\models\Categorie', 'categorie_id', 'id');

        //return $this->belongsTo(Video::class);
    }

    public function scopeSearch($query, $q){
        if($q == null) return $query;
        return $query
            ->where('title', 'LIKE', "%{$q}%")
            ->orWhere('categorie_id', 'LIKE', "%{$q}%")
            ->orWhere('rating', 'LIKE', "%{$q}%");

    }

}

app/Http/Controllers/Admin/VideoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\models\Video;
use App\models\Categorie;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class VideoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $sortBy = 'id';
        $orderBy = 'desc';
        $perPage = 20;
        $q = null;

        if($request->has('orderBy')) $orderBy = $request->query('orderBy');
        if($request->has('sortBy')) $sortBy = $request->query('sortBy');
        if($request->has('perPage')) $perPage = $request->query('perPage');
        if($request->has('q')) $q = $request->query('q');


        $videos = Video::search($q)->orderBy($sortBy, $orderBy)->paginate($perPage);
        return view('admin.videos.index', compact('videos','orderBy', 'sortBy', 'q' ,'perPage'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.videos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //dd($request);

        if($file = $request->file('videoFile')){
            $name = $file->getClientOriginalName();
            $category = (string)$request->request->get('categorie_id');
            $title = $request->request->get('title');

            $uniqueName = $title . $category . $name;
            //dd($uniqueName);
            //if($file->move('videos', $uniqueName)){
                if($path = $request->file('videoFile')->storeAs('public\videos', $uniqueName)){
                $request->request->add(['movie_url' => $uniqueName]);

                Video::create($request->except('videoFile'));
                return redirect()->route('admin.videos.index');
            };
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Video  $video
     * @return Response
     */
    public function show(Video $video)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Video  $video
     * @return Response
     */
    public function edit(Video $video)
    {

        return view('admin.videos.edit', compact('video'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  \App\Video  $video
     * @return Response
     */
    public function update(Request $request, Video $video)
    {
        $video->update($request->all());
        return redirect()->route('admin.videos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Video  $video
     * @return Response
     */
    public function destroy(Video $video)
    {
        //dd($video);
        $fileToDel = $video->getAttributeValue('movie_url');
        //dd('public/videos/'.$fileToDel);
        Storage::delete('public\videos/'.$fileToDel);

        $video->delete();

        return redirect()->route('admin.videos.index');
    }
}

resources/views/admin/videos/create.blade.php
@extends('layouts.adminlayout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Nieuwe video toevoegen</div>

                <div class="card-body">

                    <form method="POST" action="{{route('admin.videos.store')}}" enctype="multipart/form-data" name="videoFileForm">
                        @csrf
                        <div class="field">
                            Video bestand:

                            <input type="file" name="videoFile" id="inputFile" value="" class="input" />
                            <br />
                            Title:
                            <input type="text" name="title" class="form-control" />
                            Categorie:
{{--                            <input type="text" name="categorie_id" class="form-control" />--}}

                            <div class="form-group">
{{--                                <label for="sel1">Select list:</label>--}}
                                <select class="form-control" id="selectCategory" name="categorie_id">
                                    <option value="1">Manueel</option>
                                    <option value="2">Oraal</option>
                                    <option value="3">Penetratie</option>
                                    <option value="4">Holebi</option>
                                </select>
                            </div>

                            Beschrijving:
                            <input type="text" name="description" class="form-control" />
                            Rating:
                            <input type="text" name="rating" class="form-control" />

                            <br />

                            <input type="submit" value="Bewaar" id="createVideoFileFormSubmitBtn" class="btn btn-primary"/>
                            <a value="Annuleer" class="btn btn-primary btn-close" href="{{route('admin.videos.index')}}"> Annuleer</a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/videos/edit.blade.php
@extends('layouts.adminlayout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Video aanpassen</div>

                <div class="card-body">

                    <form method="POST" action="{{ route('admin.videos.update', $video->id) }}">
                        {{ method_field('PUT') }}
                        @csrf
                        Title:
                        <input type="text" name="title" value="{{$video->title}}" class="form-control" />
                        Categorie:
                        <div class="form-group">
                            {{--                                <label for="sel1">Select list:</label>--}}
                            <select class="form-control" id="selectCategory" name="categorie_id">
                                <option value="{{$video->categorie_id}}" selected></option>
                                <option value="1">Manueel</option>
                                <option value="2">Oraal</option>
                                <option value="3">Penetratie</option>
                                <option value="4">Holebi</option>
                            </select>
                        </div>
                        Beschrijving:
                        <input type="text" name="description" value="{{$video->description}}" class="form-control" />
                        Rating:
                        <input type="text" name="rating" value="{{$video->rating}}" class="form-control" />
                        <br />
                        Videobestandsnaam:
                        <label>{{$video->movie_url}}</label>

                        <br />

                        <input type="submit" value="Bewaar" class="btn btn-primary"/>
                        <a value="Annuleer" class="btn btn-primary btn-close" href="{{route('admin.videos.index')}}"> Annuleer</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/videos/index.blade.php
@extends('layouts.adminlayout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Video's</div>

                <div class="card-body">

                    <a href="{{route('admin.videos.create')}}" class="btn btn-sm btn-primary">Nieuwe video toevoegen</a>
                    <br /><br />

                    <form action="{{route('admin.videos.index')}}">
                        <div class="row">
                            <div class="col-md-4">
                                <input class="form-control form-control-sm" type="search" name="q" value="{{ $q }}">
                            </div>

                            <div class="col-md-2 col-3">
                                <select name="sortBy" class="form-control form-control-sm" value="{{ $sortBy }}">
                                    @foreach(['title','categorie_id','rating'] as $col)
                                        <option @if($col==$sortBy) selected @endif value="{{$col}}">{{ucfirst($col)}}</option>
                                        @endforeach
                                    </select>
                            </div>

                            <div class="col-md-2 col-3">
                                <select name="orderBy" class="form-control form-control-sm" value ="{{$orderBy}}">
                                    @foreach(['asc','desc'] as $order)
                                        <option @if($order==$orderBy) selected @endif value="{{$order}}">{{ucfirst($order)}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="col-md-2 col-3">
                                <select name="perPage" class="form-control form-control-sm" value ="{{$perPage}}">
                                    @foreach(['20','50','100','250'] as $page)
                                        <option @if($page==$perPage) selected @endif value="{{$page}}">{{ucfirst($page)}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="col-md-2 col-3">
                                <button type="submit" class="w-100 btn btn-sm btn-primary">Filter</button>
                            </div>

                        </div>
                    </form>

                    <table class="table">
                        <tr>
                            <th>Titel</th>
                            <th>Categorie</th>
                            <th>Rating</th>
                            <th></th>
                        </tr>
                        @forelse($videos as $video)
                            <tr>
                                <td>
                                    {{ $video->title }}
                                </td>
                                <td>
                                    {{ $video->categorie_id }}
                                </td>
                                <td>
                                    {{ $video->rating }}
                                </td>
                                <td>
                                    <a href="{{ route('admin.videos.edit', $video->id) }}" class="btn btn-sm btn-info">Edit</a>
                                    <form method="POST" action="{{ route('admin.videos.destroy', $video->id) }}">
                                        @csrf
                                        {{ method_field('DELETE') }}
                                        <input type="submit" value="Delete" onclick="return confirm('Weet u zeker dat u de video wilt verwijderen?')"
                                               class="btn btn-sm btn-danger" />
                                    </form>
                                </td>
                            </tr>
                            @empty
                        <tr>
                            <td colspan="2">
                                Geen video's gevonden.
                            </td>
                        </tr>
                            @endforelse
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection