routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('SeksEd');

Route::get('/videos/get/{id}', 'PagesController@getMoviesByCategory');

Route::get('/info', 'PagesController@showInfo');
Route::get('/vagina', 'PagesController@showVagina');
Route::get('/penis', 'PagesController@showPenis');

Route::get('/info/admin', 'PagesController@showAdmin');

//Route::resource('/movies', 'MoviesController');

//Route::post('/movies', 'MoviesController@store');

//Route::get('get-video/{video}', 'MoviesController@getVideo')->name('getVideo');

/*Route::get('/upload/something', [
    'as' => 'movie',
    'uses' => 'MoviesController@show'
]);*/


Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function(){
    Route::resource('videos', 'Admin\VideoController');
    Route::resource('links', 'Admin\LinkController');
    Route::resource('info', 'Admin\InfoController');
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
});

resources/views/layouts/adminlayout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>

            {{--                enkel zichtbaar voor ingelogd --}}
            @Auth
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/home">
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('admin.videos.index') }}">
                                Videos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('admin.links.index') }}">
                                Links
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('admin.info.index') }}">
                                Info
                            </a>
                        </li>
                    </ul>
                @endauth
                <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            {{--<li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>--}}
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else

                            <li class="nav-item">
                                {{--<a class="nav-link" href="#" role="button">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>--}}
                                <a href="{{ route('logout') }}" class="nav-link" role="button"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </li>
                            {{--<li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>--}}
                        @endguest
                    </ul>
                </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>

</html>

resources/views/layouts/mainlayout.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    {{--required meta-tags--}}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', 'Default')</title>

    <link rel="stylesheet" href="{{ mix('css/app.css') }}">

</head>
<body>
<header>
    @yield('header')
</header>

<div class="container">
    @yield('content')
</div>

</body>

<footer class="page-footer font-small mdb-color lighten-3 pt-4">
    <div class="container">
        <hr>
        <div class="d-flex justify-content-center">
            <div class="row ">
                <div class="d-flex align-items-center">

                    <div class="col-6">
                        <a href="http://aditivzw.be/nl/" target="_blank"><img class="img-fluid footerImage" src="{{asset('img/logos/logo_aditi.png')}}" alt="Aditi vzw"/></a>
                    </div>

                    <div class="col-6">
                        <a href="https://www.ucll.be/" target="_blank"><img class="img-fluid footerImage" src="{{asset('img/logos/logo_ucll.png')}}" alt="UCLL" /></a>
                    </div>

                </div>
            </div>
        </div>

        <div class="footer-copyright text-center py-3">
            © 2019 Copyright<a href=""> </a>
            <p>Deze website is gemaakt door Verleene Mark in samenwerking met Enckels Liza, Hermans Lotte en Lenskens Marten</p>
        </div>

    </div>
</footer>

<script src="{{ mix('js/app.js') }}" type="text/javascript" ></script>

@yield('scriptsToLoad')

</html>